variable "aws_region" {}
variable "s3_bucket_names" {}
variable "s3_bucket_name" {}
variable "s3_versioning" {}
variable "enable_lifecycle_rule" {}
variable "db_table_name" {}
variable "billing_mode" {}
variable "hash_key" {}
variable "attr_name" {}
variable "attr_type" {}